build:
    dependencies:
        before:
            - composer require --dev spryker/console
            - sed -i -e 's/"Spryker"\:/""\:/g' composer.json
            - APPLICATION_STORE=DE APPLICATION_ENV=development vendor/bin/console transfer:generate
    environment:
        php:
            version: 7.1
checks:
    php:
        code_rating: true

filter:
    excluded_paths:
        - config/*
        - tests/*
